version: 2
jobs:
  build:
    working_directory: ~/ivac-riffy
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: List Active Files
          command: ls files/
      - run:
          name: Combine all files to releases
          command: cat files/* > release/vtbb.sct
      - store_artifacts:
          path: /root/ivac-riffy/release/vtbb.sct
    