version: 2
jobs:
  build:
    working_directory: ~/ivac-vtbb
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install packages
          command: apk add --no-progress --no-cache ca-certificates git openssh nodejs npm
      - checkout
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Build sector file
          command: npm run build
      - run:
          name: Test sector file
          command: npm test
      - store_artifacts:
          path: /root/ivac-vtbb/result
