version: 2
jobs:
  build:
    working_directory: ~/ivac-vtbb
    docker:
      - image: rayriffy/yarn:latest
    steps:
      - checkout
      - run:
          name: Install NPM packages
          command: yarn
      - run:
          name: Build scripts
          command: yarn run tsc
      - run:
          name: Build sector file
          command: yarn run build
      - run:
          name: Test sector file
          command: yarn test
      - store_artifacts:
          path: /root/ivac-vtbb/result
