version: 2
jobs:
  build:
    working_directory: ~/ivac-riffy
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: List Active Files
          command: ls files/
      - run:
          name: Creating directory
          command: mkdir result
      - run:
          name: Combine all files
          command: cat files/* > result/vtbb.sct
      - store_artifacts:
          path: /root/ivac-riffy/result/vtbb.sct
    