version: 2
jobs:
  build:
    working_directory: ~/ivac-riffy
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Update Container
          command: apt-get update
      - run:
          name: Install packages
          command: apt-get install -y ca-certificates rsync
      - run:
          name: Create build directory
          command: mkdir build
      - run:
          name: Copy 1 2 3 4 5 6 9
          command: rsync -av --progress files/ build/ --exclude files/SID --exclude files/STAR
      - run:
          name: Create 7-SID
          command: cat files/SID/* > build/7-SID
      - run:
          name: Create 8-SID
          command: cat files/STAR/* > build/8-STAR
      - run:
          name: List Active Builds
          command: ls build/
      - run:
          name: Create result directory
          command: mkdir result
      - run:
          name: Combine all files
          command: cat build/* > result/vtbb.sct
      - store_artifacts:
          path: /root/ivac-riffy/result/vtbb.sct
    